spring.application.name=employee_management

# Mặc định dev
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Nap file .env neu co (optional: khong co file van chay binh thuong)
spring.config.import=optional:file:.env[.properties]

management.endpoints.web.exposure.include=health,metrics

# TTL cho cache (Caffeine)
app.cache.default-ttl=1m

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}


