# DataSource (dev)
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&allowPublicKeyRetrieval=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate (dev) - update tự động tạo/sửa bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Chạy data.sql (seed ADMIN) sau khi Hibernate tạo bảng xong - mặc định data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Log chi tiết
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.employee_management=DEBUG

management.endpoint.health.show-details=always
