# DataSource (prod)
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&allowPublicKeyRetrieval=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate (prod)
# validate: Không cho Hibernate tự động sửa schema production
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Giảm bớt log
logging.level.root=WARN
logging.level.com.employee_management=INFO

management.endpoint.health.show-details=never
